// Comprehensive food calorie database
// All values are per common serving size
// Sources: USDA FoodData Central, nutritionix

export const FOODS = [
  // ─── Grains & Carbs ───────────────────────────────────
  { name: 'White Rice', unit: 'cup (cooked)', cal: 206 },
  { name: 'Brown Rice', unit: 'cup (cooked)', cal: 216 },
  { name: 'Fried Rice', unit: 'cup', cal: 298 },
  { name: 'Sinangag (Garlic Fried Rice)', unit: 'cup', cal: 280 },
  { name: 'White Bread', unit: 'slice (30g)', cal: 79 },
  { name: 'Whole Wheat Bread', unit: 'slice (30g)', cal: 68 },
  { name: 'Pandesal', unit: 'piece (50g)', cal: 145 },
  { name: 'Ensaymada', unit: 'piece (80g)', cal: 290 },
  { name: 'Spaghetti (cooked)', unit: 'cup (140g)', cal: 220 },
  { name: 'Pasta (cooked)', unit: 'cup (140g)', cal: 220 },
  { name: 'Oatmeal', unit: 'cup (cooked)', cal: 158 },
  { name: 'Pancake', unit: 'piece (70g)', cal: 180 },
  { name: 'Croissant', unit: 'piece (60g)', cal: 231 },
  { name: 'Muffin (blueberry)', unit: 'piece (110g)', cal: 350 },
  { name: 'Granola', unit: '¼ cup (30g)', cal: 130 },
  { name: 'Quinoa (cooked)', unit: 'cup', cal: 222 },
  { name: 'Bagel', unit: 'piece (100g)', cal: 270 },
  { name: 'Tortilla (flour)', unit: 'piece (45g)', cal: 140 },
  { name: 'Pizza (cheese)', unit: 'slice (107g)', cal: 285 },
  { name: 'Burger Bun', unit: 'piece (45g)', cal: 120 },

  // ─── Proteins ──────────────────────────────────────────
  { name: 'Chicken Breast (grilled)', unit: '100g', cal: 165 },
  { name: 'Chicken Thigh (grilled)', unit: '100g', cal: 209 },
  { name: 'Fried Chicken (piece)', unit: 'piece (120g)', cal: 330 },
  { name: 'Tinola (chicken)', unit: 'cup', cal: 180 },
  { name: 'Adobo (chicken)', unit: 'cup', cal: 290 },
  { name: 'Lechon Manok', unit: '100g', cal: 220 },
  { name: 'Ground Beef (cooked)', unit: '100g', cal: 254 },
  { name: 'Beef Steak', unit: '100g', cal: 271 },
  { name: 'Beef Tapa', unit: '100g', cal: 240 },
  { name: 'Beef Kaldereta', unit: 'cup', cal: 320 },
  { name: 'Pork Belly (liempo)', unit: '100g', cal: 395 },
  { name: 'Pork Chop (grilled)', unit: '100g', cal: 231 },
  { name: 'Pork Adobo', unit: 'cup', cal: 350 },
  { name: 'Sinigang (pork)', unit: 'cup', cal: 220 },
  { name: 'Lechon (pork)', unit: '100g', cal: 320 },
  { name: 'Longganisa', unit: 'piece (50g)', cal: 180 },
  { name: 'Tocino (pork)', unit: '100g', cal: 260 },
  { name: 'Salmon (baked)', unit: '100g', cal: 208 },
  { name: 'Tilapia (grilled)', unit: '100g', cal: 128 },
  { name: 'Bangus (milkfish, grilled)', unit: '100g', cal: 148 },
  { name: 'Tuna (canned in water)', unit: '100g', cal: 116 },
  { name: 'Tuna (canned in oil)', unit: '100g', cal: 198 },
  { name: 'Shrimp (cooked)', unit: '100g', cal: 99 },
  { name: 'Danggit (dried fish)', unit: 'piece (20g)', cal: 70 },
  { name: 'Sardines (canned)', unit: '100g', cal: 208 },
  { name: 'Tuyo (dried herring)', unit: 'piece (20g)', cal: 64 },
  { name: 'Egg (whole, boiled)', unit: 'piece (50g)', cal: 78 },
  { name: 'Egg (scrambled)', unit: 'piece (61g)', cal: 91 },
  { name: 'Egg (fried)', unit: 'piece (46g)', cal: 90 },
  { name: 'Egg White', unit: 'piece', cal: 17 },
  { name: 'Tokwa (tofu, firm)', unit: '100g', cal: 76 },
  { name: 'Tofu (silken)', unit: '100g', cal: 40 },

  // ─── Vegetables ────────────────────────────────────────
  { name: 'Kangkong (water spinach)', unit: 'cup (cooked)', cal: 20 },
  { name: 'Pechay (bok choy)', unit: 'cup (cooked)', cal: 20 },
  { name: 'Broccoli (steamed)', unit: 'cup (91g)', cal: 31 },
  { name: 'Spinach (cooked)', unit: 'cup (180g)', cal: 41 },
  { name: 'Cabbage (cooked)', unit: 'cup (150g)', cal: 33 },
  { name: 'Eggplant (cooked)', unit: 'cup (99g)', cal: 35 },
  { name: 'Ampalaya (bitter melon)', unit: 'cup (cooked)', cal: 18 },
  { name: 'Sitaw (string beans)', unit: 'cup (cooked)', cal: 44 },
  { name: 'Carrots (cooked)', unit: 'cup (156g)', cal: 54 },
  { name: 'Sweet Potato (boiled)', unit: 'cup (200g)', cal: 180 },
  { name: 'Potato (boiled)', unit: 'cup (156g)', cal: 134 },
  { name: 'Tomato', unit: 'medium (123g)', cal: 22 },
  { name: 'Onion', unit: 'medium (110g)', cal: 44 },
  { name: 'Garlic', unit: 'clove (3g)', cal: 4 },
  { name: 'Malunggay (moringa)', unit: 'cup leaves (21g)', cal: 13 },
  { name: 'Peas (green, cooked)', unit: 'cup (160g)', cal: 134 },
  { name: 'Corn (cooked)', unit: 'ear (90g)', cal: 77 },
  { name: 'Mushroom (cooked)', unit: 'cup (156g)', cal: 44 },
  { name: 'Bell Pepper', unit: 'piece (120g)', cal: 31 },
  { name: 'Cucumber', unit: 'cup (119g)', cal: 16 },

  // ─── Fruits ────────────────────────────────────────────
  { name: 'Banana (lakatan)', unit: 'piece (118g)', cal: 105 },
  { name: 'Banana (saba, cooked)', unit: 'piece (80g)', cal: 88 },
  { name: 'Mango (fresh)', unit: 'cup (165g)', cal: 99 },
  { name: 'Apple', unit: 'medium (182g)', cal: 95 },
  { name: 'Orange', unit: 'medium (131g)', cal: 62 },
  { name: 'Watermelon', unit: 'cup (152g)', cal: 46 },
  { name: 'Papaya', unit: 'cup (140g)', cal: 62 },
  { name: 'Grapes', unit: 'cup (92g)', cal: 62 },
  { name: 'Strawberries', unit: 'cup (152g)', cal: 49 },
  { name: 'Blueberries', unit: 'cup (148g)', cal: 84 },
  { name: 'Avocado', unit: 'half (68g)', cal: 114 },
  { name: 'Pineapple', unit: 'cup (165g)', cal: 82 },
  { name: 'Melon (cantaloupe)', unit: 'cup (160g)', cal: 54 },
  { name: 'Lychee', unit: 'cup (190g)', cal: 125 },
  { name: 'Jackfruit (langka)', unit: 'cup (165g)', cal: 155 },

  // ─── Dairy & Alternatives ──────────────────────────────
  { name: 'Whole Milk', unit: 'cup (244ml)', cal: 149 },
  { name: 'Skim Milk', unit: 'cup (244ml)', cal: 83 },
  { name: 'Evaporated Milk', unit: 'cup (252ml)', cal: 338 },
  { name: 'Greek Yogurt (plain)', unit: '170g container', cal: 100 },
  { name: 'Yogurt (low-fat)', unit: '170g container', cal: 100 },
  { name: 'Cheese (cheddar)', unit: 'slice (28g)', cal: 113 },
  { name: 'Cheese (Eden/processed)', unit: 'slice (21g)', cal: 70 },
  { name: 'Butter', unit: 'tbsp (14g)', cal: 100 },
  { name: 'Cream (heavy)', unit: 'tbsp (15ml)', cal: 52 },
  { name: 'Almond Milk', unit: 'cup (240ml)', cal: 39 },
  { name: 'Coconut Milk (canned)', unit: '100ml', cal: 197 },

  // ─── Soups & Stews ─────────────────────────────────────
  { name: 'Sinigang (bangus)', unit: 'cup', cal: 180 },
  { name: 'Sinigang (hipon/shrimp)', unit: 'cup', cal: 120 },
  { name: 'Nilaga (beef)', unit: 'cup', cal: 220 },
  { name: 'Bulalo', unit: 'cup', cal: 280 },
  { name: 'Kare-kare', unit: 'cup', cal: 310 },
  { name: 'Chicken Soup (arroz caldo)', unit: 'cup', cal: 200 },
  { name: 'Lugaw', unit: 'cup', cal: 130 },
  { name: 'Champorado', unit: 'cup', cal: 220 },
  { name: 'Tom Yum Soup', unit: 'cup', cal: 96 },
  { name: 'Miso Soup', unit: 'cup (240ml)', cal: 40 },
  { name: 'Chicken Noodle Soup', unit: 'cup', cal: 74 },

  // ─── Snacks & Junk Food ────────────────────────────────
  { name: 'Chips (Pringles)', unit: '16 chips (30g)', cal: 150 },
  { name: 'Crackers (SkyFlakes)', unit: 'pack (30g)', cal: 120 },
  { name: 'Peanuts (roasted)', unit: '¼ cup (36g)', cal: 207 },
  { name: 'Cashews', unit: '¼ cup (32g)', cal: 188 },
  { name: 'Almonds', unit: '¼ cup (35g)', cal: 206 },
  { name: 'Dark Chocolate', unit: 'square (10g)', cal: 53 },
  { name: 'Milk Chocolate', unit: 'square (10g)', cal: 54 },
  { name: 'Popcorn (air-popped)', unit: 'cup (8g)', cal: 31 },
  { name: 'Turon', unit: 'piece (80g)', cal: 185 },
  { name: 'Banana Cue', unit: 'piece (100g)', cal: 190 },
  { name: 'Ice Cream (vanilla)', unit: '½ cup (66g)', cal: 137 },
  { name: 'Halo-halo', unit: 'cup', cal: 300 },
  { name: 'Leche Flan', unit: 'piece (100g)', cal: 220 },
  { name: 'Polvoron', unit: 'piece (25g)', cal: 115 },
  { name: 'Bibingka', unit: 'piece (120g)', cal: 290 },
  { name: 'Puto', unit: 'piece (30g)', cal: 70 },
  { name: 'Kutsinta', unit: 'piece (40g)', cal: 80 },

  // ─── Drinks ────────────────────────────────────────────
  { name: 'Water', unit: 'glass (240ml)', cal: 0 },
  { name: 'Brewed Coffee (black)', unit: 'cup (240ml)', cal: 2 },
  { name: 'Coffee with Milk & Sugar', unit: 'cup', cal: 60 },
  { name: 'Kapeng Barako', unit: 'cup', cal: 5 },
  { name: '3-in-1 Coffee (Nescafe)', unit: 'sachet', cal: 80 },
  { name: 'Milk Tea (medium)', unit: '500ml', cal: 300 },
  { name: 'Coke (regular)', unit: 'can (330ml)', cal: 139 },
  { name: 'Coke (zero)', unit: 'can (330ml)', cal: 1 },
  { name: 'Sprite', unit: 'can (330ml)', cal: 131 },
  { name: 'Orange Juice', unit: 'cup (240ml)', cal: 112 },
  { name: 'Buko Juice', unit: 'cup (240ml)', cal: 45 },
  { name: 'Calamansi Juice', unit: 'cup (240ml)', cal: 35 },
  { name: 'Beer (San Miguel)', unit: 'bottle (330ml)', cal: 145 },
  { name: 'Red Wine', unit: 'glass (148ml)', cal: 125 },
  { name: 'Protein Shake', unit: 'scoop (30g in water)', cal: 120 },
  { name: 'Coconut Water', unit: 'cup (240ml)', cal: 46 },
  { name: 'Green Tea', unit: 'cup (240ml)', cal: 2 },
  { name: 'Milo (with milk)', unit: 'cup', cal: 170 },

  // ─── Fast Food & Restaurants ──────────────────────────
  { name: 'Jollibee Chickenjoy (1pc)', unit: 'piece', cal: 380 },
  { name: 'Jollibee Yumburger', unit: 'piece', cal: 400 },
  { name: 'McDouble Burger', unit: 'piece', cal: 390 },
  { name: 'French Fries (medium)', unit: 'serving (117g)', cal: 365 },
  { name: 'Spaghetti (Jollibee)', unit: 'serving', cal: 396 },
  { name: 'Hotdog (plain)', unit: 'piece (57g)', cal: 180 },
  { name: 'Ham (sandwich)', unit: 'slice (28g)', cal: 46 },
  { name: 'Spam (1 slice)', unit: 'slice (56g)', cal: 174 },
  { name: 'Vienna Sausage (canned)', unit: '3 pieces (48g)', cal: 130 },

  // ─── Condiments & Fats ─────────────────────────────────
  { name: 'Cooking Oil', unit: 'tbsp (14ml)', cal: 124 },
  { name: 'Olive Oil', unit: 'tbsp (14ml)', cal: 119 },
  { name: 'Mayonnaise', unit: 'tbsp (14g)', cal: 94 },
  { name: 'Ketchup', unit: 'tbsp (17g)', cal: 19 },
  { name: 'Soy Sauce', unit: 'tbsp (16ml)', cal: 8 },
  { name: 'Fish Sauce (patis)', unit: 'tbsp (16ml)', cal: 6 },
  { name: 'Vinegar', unit: 'tbsp (15ml)', cal: 3 },
  { name: 'Peanut Butter', unit: 'tbsp (16g)', cal: 96 },
  { name: 'Honey', unit: 'tbsp (21g)', cal: 64 },
  { name: 'Sugar (white)', unit: 'tbsp (12g)', cal: 46 },
];

// Calorie budget levels
export const CALORIE_BUDGETS = [
  { label: 'Lose weight (light)', cal: 1500 },
  { label: 'Lose weight', cal: 1700 },
  { label: 'Maintain weight', cal: 2000 },
  { label: 'Gain muscle (light)', cal: 2300 },
  { label: 'Gain muscle', cal: 2700 },
  { label: 'Custom', cal: null },
];

export const MEAL_SLOTS = ['Breakfast','Lunch','Dinner','Snack'];
export const SLOT_META = {
  Breakfast: { icon: 'sun',      color: '#FF9500', time: '7–9 AM' },
  Lunch:     { icon: 'utensils', color: '#FF5757', time: '12–1 PM' },
  Dinner:    { icon: 'moon',     color: '#9B6FFF', time: '6–8 PM' },
  Snack:     { icon: 'leaf',     color: '#22C792', time: 'Any time' },
};