// Comprehensive food calorie + protein database
// Values per common serving size
// Sources: USDA FoodData Central, Nutritionix, Philippine Food Composition Tables

export const FOODS = [
  // ─── Grains & Carbs ───────────────────────────────────
  { name: 'White Rice', unit: 'cup (cooked)', cal: 206, protein: 4.3 },
  { name: 'Brown Rice', unit: 'cup (cooked)', cal: 216, protein: 5.0 },
  { name: 'Fried Rice', unit: 'cup', cal: 298, protein: 6.2 },
  { name: 'Sinangag (Garlic Fried Rice)', unit: 'cup', cal: 280, protein: 5.4 },
  { name: 'White Bread', unit: 'slice (30g)', cal: 79, protein: 2.7 },
  { name: 'Whole Wheat Bread', unit: 'slice (30g)', cal: 68, protein: 3.6 },
  { name: 'Pandesal', unit: 'piece (50g)', cal: 145, protein: 4.5 },
  { name: 'Ensaymada', unit: 'piece (80g)', cal: 290, protein: 5.2 },
  { name: 'Spaghetti (cooked)', unit: 'cup (140g)', cal: 220, protein: 8.1 },
  { name: 'Pasta (cooked)', unit: 'cup (140g)', cal: 220, protein: 8.1 },
  { name: 'Oatmeal', unit: 'cup (cooked)', cal: 158, protein: 5.9 },
  { name: 'Pancake', unit: 'piece (70g)', cal: 180, protein: 4.8 },
  { name: 'Croissant', unit: 'piece (60g)', cal: 231, protein: 4.7 },
  { name: 'Muffin (blueberry)', unit: 'piece (110g)', cal: 350, protein: 5.0 },
  { name: 'Granola', unit: '¼ cup (30g)', cal: 130, protein: 3.1 },
  { name: 'Quinoa (cooked)', unit: 'cup', cal: 222, protein: 8.1 },
  { name: 'Bagel', unit: 'piece (100g)', cal: 270, protein: 10.5 },
  { name: 'Tortilla (flour)', unit: 'piece (45g)', cal: 140, protein: 3.6 },
  { name: 'Pizza (cheese)', unit: 'slice (107g)', cal: 285, protein: 12.2 },
  { name: 'Burger Bun', unit: 'piece (45g)', cal: 120, protein: 4.0 },

  // ─── Proteins ──────────────────────────────────────────
  { name: 'Chicken Breast (grilled)', unit: '100g', cal: 165, protein: 31.0 },
  { name: 'Chicken Thigh (grilled)', unit: '100g', cal: 209, protein: 26.0 },
  { name: 'Fried Chicken (piece)', unit: 'piece (120g)', cal: 330, protein: 24.8 },
  { name: 'Tinola (chicken)', unit: 'cup', cal: 180, protein: 16.5 },
  { name: 'Adobo (chicken)', unit: 'cup', cal: 290, protein: 24.0 },
  { name: 'Lechon Manok', unit: '100g', cal: 220, protein: 25.2 },
  { name: 'Ground Beef (cooked)', unit: '100g', cal: 254, protein: 26.1 },
  { name: 'Beef Steak', unit: '100g', cal: 271, protein: 26.3 },
  { name: 'Beef Tapa', unit: '100g', cal: 240, protein: 22.0 },
  { name: 'Beef Kaldereta', unit: 'cup', cal: 320, protein: 20.4 },
  { name: 'Pork Belly (liempo)', unit: '100g', cal: 395, protein: 14.0 },
  { name: 'Pork Chop (grilled)', unit: '100g', cal: 231, protein: 25.7 },
  { name: 'Pork Adobo', unit: 'cup', cal: 350, protein: 22.5 },
  { name: 'Sinigang (pork)', unit: 'cup', cal: 220, protein: 14.8 },
  { name: 'Lechon (pork)', unit: '100g', cal: 320, protein: 21.0 },
  { name: 'Longganisa', unit: 'piece (50g)', cal: 180, protein: 7.2 },
  { name: 'Tocino (pork)', unit: '100g', cal: 260, protein: 16.5 },
  { name: 'Salmon (baked)', unit: '100g', cal: 208, protein: 25.4 },
  { name: 'Tilapia (grilled)', unit: '100g', cal: 128, protein: 26.2 },
  { name: 'Bangus (milkfish, grilled)', unit: '100g', cal: 148, protein: 21.0 },
  { name: 'Tuna (canned in water)', unit: '100g', cal: 116, protein: 25.5 },
  { name: 'Tuna (canned in oil)', unit: '100g', cal: 198, protein: 22.0 },
  { name: 'Shrimp (cooked)', unit: '100g', cal: 99, protein: 20.9 },
  { name: 'Danggit (dried fish)', unit: 'piece (20g)', cal: 70, protein: 13.2 },
  { name: 'Sardines (canned)', unit: '100g', cal: 208, protein: 24.6 },
  { name: 'Tuyo (dried herring)', unit: 'piece (20g)', cal: 64, protein: 11.8 },
  { name: 'Egg (whole, boiled)', unit: 'piece (50g)', cal: 78, protein: 6.3 },
  { name: 'Egg (scrambled)', unit: 'piece (61g)', cal: 91, protein: 6.1 },
  { name: 'Egg (fried)', unit: 'piece (46g)', cal: 90, protein: 6.3 },
  { name: 'Egg White', unit: 'piece', cal: 17, protein: 3.6 },
  { name: 'Tokwa (tofu, firm)', unit: '100g', cal: 76, protein: 8.1 },
  { name: 'Tofu (silken)', unit: '100g', cal: 40, protein: 4.8 },

  // ─── Vegetables ────────────────────────────────────────
  { name: 'Kangkong (water spinach)', unit: 'cup (cooked)', cal: 20, protein: 2.6 },
  { name: 'Pechay (bok choy)', unit: 'cup (cooked)', cal: 20, protein: 2.6 },
  { name: 'Broccoli (steamed)', unit: 'cup (91g)', cal: 31, protein: 2.6 },
  { name: 'Spinach (cooked)', unit: 'cup (180g)', cal: 41, protein: 5.4 },
  { name: 'Cabbage (cooked)', unit: 'cup (150g)', cal: 33, protein: 1.9 },
  { name: 'Eggplant (cooked)', unit: 'cup (99g)', cal: 35, protein: 0.8 },
  { name: 'Ampalaya (bitter melon)', unit: 'cup (cooked)', cal: 18, protein: 1.6 },
  { name: 'Sitaw (string beans)', unit: 'cup (cooked)', cal: 44, protein: 2.4 },
  { name: 'Carrots (cooked)', unit: 'cup (156g)', cal: 54, protein: 1.2 },
  { name: 'Sweet Potato (boiled)', unit: 'cup (200g)', cal: 180, protein: 4.0 },
  { name: 'Potato (boiled)', unit: 'cup (156g)', cal: 134, protein: 2.9 },
  { name: 'Tomato', unit: 'medium (123g)', cal: 22, protein: 1.1 },
  { name: 'Onion', unit: 'medium (110g)', cal: 44, protein: 1.2 },
  { name: 'Garlic', unit: 'clove (3g)', cal: 4, protein: 0.2 },
  { name: 'Malunggay (moringa)', unit: 'cup leaves (21g)', cal: 13, protein: 1.9 },
  { name: 'Peas (green, cooked)', unit: 'cup (160g)', cal: 134, protein: 8.6 },
  { name: 'Corn (cooked)', unit: 'ear (90g)', cal: 77, protein: 2.9 },
  { name: 'Mushroom (cooked)', unit: 'cup (156g)', cal: 44, protein: 3.4 },
  { name: 'Bell Pepper', unit: 'piece (120g)', cal: 31, protein: 1.0 },
  { name: 'Cucumber', unit: 'cup (119g)', cal: 16, protein: 0.7 },

  // ─── Fruits ────────────────────────────────────────────
  { name: 'Banana (lakatan)', unit: 'piece (118g)', cal: 105, protein: 1.3 },
  { name: 'Banana (saba, cooked)', unit: 'piece (80g)', cal: 88, protein: 0.9 },
  { name: 'Mango (fresh)', unit: 'cup (165g)', cal: 99, protein: 1.4 },
  { name: 'Apple', unit: 'medium (182g)', cal: 95, protein: 0.5 },
  { name: 'Orange', unit: 'medium (131g)', cal: 62, protein: 1.2 },
  { name: 'Watermelon', unit: 'cup (152g)', cal: 46, protein: 0.9 },
  { name: 'Papaya', unit: 'cup (140g)', cal: 62, protein: 0.7 },
  { name: 'Grapes', unit: 'cup (92g)', cal: 62, protein: 0.6 },
  { name: 'Strawberries', unit: 'cup (152g)', cal: 49, protein: 1.0 },
  { name: 'Blueberries', unit: 'cup (148g)', cal: 84, protein: 1.1 },
  { name: 'Avocado', unit: 'half (68g)', cal: 114, protein: 1.3 },
  { name: 'Pineapple', unit: 'cup (165g)', cal: 82, protein: 0.9 },
  { name: 'Melon (cantaloupe)', unit: 'cup (160g)', cal: 54, protein: 1.3 },
  { name: 'Lychee', unit: 'cup (190g)', cal: 125, protein: 1.6 },
  { name: 'Jackfruit (langka)', unit: 'cup (165g)', cal: 155, protein: 2.8 },

  // ─── Dairy & Alternatives ──────────────────────────────
  { name: 'Whole Milk', unit: 'cup (244ml)', cal: 149, protein: 8.0 },
  { name: 'Skim Milk', unit: 'cup (244ml)', cal: 83, protein: 8.4 },
  { name: 'Evaporated Milk', unit: 'cup (252ml)', cal: 338, protein: 17.2 },
  { name: 'Greek Yogurt (plain)', unit: '170g container', cal: 100, protein: 17.0 },
  { name: 'Yogurt (low-fat)', unit: '170g container', cal: 100, protein: 8.5 },
  { name: 'Cheese (cheddar)', unit: 'slice (28g)', cal: 113, protein: 7.0 },
  { name: 'Cheese (Eden/processed)', unit: 'slice (21g)', cal: 70, protein: 4.2 },
  { name: 'Butter', unit: 'tbsp (14g)', cal: 100, protein: 0.1 },
  { name: 'Cream (heavy)', unit: 'tbsp (15ml)', cal: 52, protein: 0.3 },
  { name: 'Almond Milk', unit: 'cup (240ml)', cal: 39, protein: 1.5 },
  { name: 'Coconut Milk (canned)', unit: '100ml', cal: 197, protein: 2.1 },

  // ─── Soups & Stews ─────────────────────────────────────
  { name: 'Sinigang (bangus)', unit: 'cup', cal: 180, protein: 15.2 },
  { name: 'Sinigang (hipon/shrimp)', unit: 'cup', cal: 120, protein: 12.4 },
  { name: 'Nilaga (beef)', unit: 'cup', cal: 220, protein: 18.0 },
  { name: 'Bulalo', unit: 'cup', cal: 280, protein: 20.5 },
  { name: 'Kare-kare', unit: 'cup', cal: 310, protein: 18.2 },
  { name: 'Chicken Soup (arroz caldo)', unit: 'cup', cal: 200, protein: 12.0 },
  { name: 'Lugaw', unit: 'cup', cal: 130, protein: 4.5 },
  { name: 'Champorado', unit: 'cup', cal: 220, protein: 5.1 },
  { name: 'Tom Yum Soup', unit: 'cup', cal: 96, protein: 8.4 },
  { name: 'Miso Soup', unit: 'cup (240ml)', cal: 40, protein: 3.3 },
  { name: 'Chicken Noodle Soup', unit: 'cup', cal: 74, protein: 5.9 },

  // ─── Snacks & Desserts ─────────────────────────────────
  { name: 'Chips (Pringles)', unit: '16 chips (30g)', cal: 150, protein: 1.5 },
  { name: 'Crackers (SkyFlakes)', unit: 'pack (30g)', cal: 120, protein: 2.8 },
  { name: 'Peanuts (roasted)', unit: '¼ cup (36g)', cal: 207, protein: 9.4 },
  { name: 'Cashews', unit: '¼ cup (32g)', cal: 188, protein: 5.2 },
  { name: 'Almonds', unit: '¼ cup (35g)', cal: 206, protein: 7.5 },
  { name: 'Dark Chocolate', unit: 'square (10g)', cal: 53, protein: 0.8 },
  { name: 'Milk Chocolate', unit: 'square (10g)', cal: 54, protein: 0.6 },
  { name: 'Popcorn (air-popped)', unit: 'cup (8g)', cal: 31, protein: 1.0 },
  { name: 'Turon', unit: 'piece (80g)', cal: 185, protein: 2.1 },
  { name: 'Banana Cue', unit: 'piece (100g)', cal: 190, protein: 1.6 },
  { name: 'Ice Cream (vanilla)', unit: '½ cup (66g)', cal: 137, protein: 2.3 },
  { name: 'Halo-halo', unit: 'cup', cal: 300, protein: 5.2 },
  { name: 'Leche Flan', unit: 'piece (100g)', cal: 220, protein: 7.4 },
  { name: 'Polvoron', unit: 'piece (25g)', cal: 115, protein: 2.1 },
  { name: 'Bibingka', unit: 'piece (120g)', cal: 290, protein: 6.4 },
  { name: 'Puto', unit: 'piece (30g)', cal: 70, protein: 1.8 },
  { name: 'Kutsinta', unit: 'piece (40g)', cal: 80, protein: 0.9 },

  // ─── Drinks ────────────────────────────────────────────
  { name: 'Water', unit: 'glass (240ml)', cal: 0, protein: 0 },
  { name: 'Brewed Coffee (black)', unit: 'cup (240ml)', cal: 2, protein: 0.3 },
  { name: 'Coffee with Milk & Sugar', unit: 'cup', cal: 60, protein: 1.5 },
  { name: 'Kapeng Barako', unit: 'cup', cal: 5, protein: 0.3 },
  { name: '3-in-1 Coffee (Nescafe)', unit: 'sachet', cal: 80, protein: 1.0 },
  { name: 'Milk Tea (medium)', unit: '500ml', cal: 300, protein: 3.5 },
  { name: 'Coke (regular)', unit: 'can (330ml)', cal: 139, protein: 0 },
  { name: 'Coke (zero)', unit: 'can (330ml)', cal: 1, protein: 0 },
  { name: 'Sprite', unit: 'can (330ml)', cal: 131, protein: 0 },
  { name: 'Orange Juice', unit: 'cup (240ml)', cal: 112, protein: 1.7 },
  { name: 'Buko Juice', unit: 'cup (240ml)', cal: 45, protein: 0.5 },
  { name: 'Calamansi Juice', unit: 'cup (240ml)', cal: 35, protein: 0.5 },
  { name: 'Beer (San Miguel)', unit: 'bottle (330ml)', cal: 145, protein: 1.3 },
  { name: 'Red Wine', unit: 'glass (148ml)', cal: 125, protein: 0.1 },
  { name: 'Protein Shake', unit: 'scoop (30g in water)', cal: 120, protein: 24.0 },
  { name: 'Coconut Water', unit: 'cup (240ml)', cal: 46, protein: 1.7 },
  { name: 'Green Tea', unit: 'cup (240ml)', cal: 2, protein: 0.5 },
  { name: 'Milo (with milk)', unit: 'cup', cal: 170, protein: 6.5 },

  // ─── Fast Food & Restaurants ──────────────────────────
  { name: 'Jollibee Chickenjoy (1pc)', unit: 'piece', cal: 380, protein: 28.5 },
  { name: 'Jollibee Yumburger', unit: 'piece', cal: 400, protein: 18.2 },
  { name: 'McDouble Burger', unit: 'piece', cal: 390, protein: 22.0 },
  { name: 'French Fries (medium)', unit: 'serving (117g)', cal: 365, protein: 3.8 },
  { name: 'Spaghetti (Jollibee)', unit: 'serving', cal: 396, protein: 14.5 },
  { name: 'Hotdog (plain)', unit: 'piece (57g)', cal: 180, protein: 6.5 },
  { name: 'Ham (sandwich)', unit: 'slice (28g)', cal: 46, protein: 4.5 },
  { name: 'Spam (1 slice)', unit: 'slice (56g)', cal: 174, protein: 7.7 },
  { name: 'Vienna Sausage (canned)', unit: '3 pieces (48g)', cal: 130, protein: 5.4 },

  // ─── Condiments & Fats ─────────────────────────────────
  { name: 'Cooking Oil', unit: 'tbsp (14ml)', cal: 124, protein: 0 },
  { name: 'Olive Oil', unit: 'tbsp (14ml)', cal: 119, protein: 0 },
  { name: 'Mayonnaise', unit: 'tbsp (14g)', cal: 94, protein: 0.1 },
  { name: 'Ketchup', unit: 'tbsp (17g)', cal: 19, protein: 0.3 },
  { name: 'Soy Sauce', unit: 'tbsp (16ml)', cal: 8, protein: 1.3 },
  { name: 'Fish Sauce (patis)', unit: 'tbsp (16ml)', cal: 6, protein: 0.9 },
  { name: 'Vinegar', unit: 'tbsp (15ml)', cal: 3, protein: 0 },
  { name: 'Peanut Butter', unit: 'tbsp (16g)', cal: 96, protein: 4.0 },
  { name: 'Honey', unit: 'tbsp (21g)', cal: 64, protein: 0.1 },
  { name: 'Sugar (white)', unit: 'tbsp (12g)', cal: 46, protein: 0 },
];

// Calorie budget levels
export const CALORIE_BUDGETS = [
  { label: 'Lose weight (light)', cal: 1500 },
  { label: 'Lose weight', cal: 1700 },
  { label: 'Maintain weight', cal: 2000 },
  { label: 'Gain muscle (light)', cal: 2300 },
  { label: 'Gain muscle', cal: 2700 },
  { label: 'Custom', cal: null },
];

export const MEAL_SLOTS = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];
export const SLOT_META = {
  Breakfast: { icon: 'sun',      color: '#FF9500', time: '7–9 AM' },
  Lunch:     { icon: 'utensils', color: '#FF5757', time: '12–1 PM' },
  Dinner:    { icon: 'moon',     color: '#9B6FFF', time: '6–8 PM' },
  Snack:     { icon: 'leaf',     color: '#22C792', time: 'Any time' },
};